version: "3.8"
services:
  frps:
    container_name: frps
    image: snowdreamtech/frps:0.51.3
    network_mode: host
    volumes:
      - ./frp/frps.ini:/etc/frp/frps.ini
      - ./log/:/etc/frp/log/