version: "3.8"
services:
  nginx:
    image: nginx:1.21.6
    container_name: nginx
    environment:
      TZ: Asia/Shanghai
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # 证书映射
      - ./nginx/cert:/etc/nginx/cert
      # 配置文件映射
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # 页面目录
      - ./nginx/html:/usr/share/nginx/html
      # 日志目录
      - ./nginx/logs:/var/log/nginx
    privileged: true
    network_mode: "host"
